version: '2'

services:
  angular:
    build: angular-client # directory of necessary Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"
    volumes:
      - ./angular-client:/usr/src/app
    command: npm start

  express:
    build: express-server
    environment:
      - DB_HOST=${DB_HOST}
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./express-server:/usr/src/app
    links:
      - database
    command: npm start

  database:
    image: mongo
    ports:
      - "27017:27017"